server:
  port: 9001

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

# more configuration --> https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-discovery
