server:
  port: 8401

spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8082 # sentinel.jar server -> ip:port  default port: 8080
        port: 8719  #
# 有关DataSource的自动配置. com.alibaba.cloud.sentinel.custom.SentinelDataSourceHandler
      datasource:
        nacos-ds: # 任意名称
          nacos: # datasource 类型, zookeeper,apollo,redis,nacos等
            server-addr: localhost:8848
            data-id: sentinel-service-flow-rule-nacos-ds
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow

# Endpoint 支持
# 在使用 Endpoint 特性之前需要在 Maven 中添加 spring-boot-starter-actuator 依赖，并在配置中允许 Endpoints 的访问。
# Spring Boot 1.x 中添加配置 management.security.enabled=false。暴露的 endpoint 路径为 /sentinel
# Spring Boot 2.x 中添加配置 management.endpoints.web.exposure.include=*。暴露的 endpoint 路径为 /actuator/sentinel
# Sentinel Endpoint 里暴露的信息非常有用。包括当前应用的所有规则信息、日志目录、当前实例的 IP，Sentinel Dashboard 地址，Block Page，应用与 Sentinel Dashboard 的心跳频率等等信息。
management:
  endpoints:
    web:
      exposure:
        include: '*'
